### ISSUE TITLE
Get_snap and Open_video_stream not working

### ISSUE THREAD

**Issue by FarmRoboticist** [ReolinkCameraAPI/reolinkapipy#68]
When ever I call the Get_snap or Open_video_stream functions I keep getting these errors. I can receive data but not any video  
Here is my code:

from reolinkapi import Camera
import time

ip = "192.168.0.13"
user = "admin"
password ="FC98**"

c = Camera(ip, user, password, True, proxy={"http": "socks5://192.168.0.13:8000/"})
#c = Camera(ip, user, password, True, True, proxy={"http":"192.168.0.13"})

time.sleep(1)
#c.get_snap()
#c.logout()

print(c.get_general_system())
c.get_snap()
#c.open_video_stream
g = c.get_snap()

Here is the error im getting:

Could not get Image data
 HTTPSConnectionPool(host='192.168.0.13', port=443): Max retries exceeded with url: /cgi-bin/api.cgi?cmd=Snap&channel=0&rs=U60T7YLGDC&user=admin&password=FC98%2A%2A (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
Traceback (most recent call last):
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)  File "C:\Users\Rhys Brown\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.13', port=443): Max retries exceeded with url: /cgi-bin/api.cgi?cmd=Snap&channel=0&rs=U60T7YLGDC&user=admin&password=FC98%2A%2A (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
PS C:\Users\Rhys Brown\Documents\GitHub\Farming_AI>

**Comment by themoosman** [comment]
What happens if you change the login command to `c = Camera(ip, user, password, False, proxy={"http": "socks5://[192.168.0.13:8000/](http://192.168.0.13:8000/)"})` ?

**Comment by Benehiko** [comment]
Closing. No extra information provided.
